version: 1
services:
  - type: web
    name: hirewise-api
    env: python
    plan: starter
    runtime: python3.9
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GEMINI_API_KEY
        sync: false # Ensure API key is set in Render dashboard manually
